### ISSUE TITLE
Compress stream before writing to disk

### ISSUE THREAD

**Issue by jmakov** [jmakov/gulp#2]
This option would allow you to pipe captured stream and process it in-line, before saving it to a file. A use case is saving disk bandwidth using a fast compressor e.g. snappy before saving (from https://github.com/the-tcpdump-group/tcpdump/pull/458).

**Comment by mcr** [comment]
Since there is a pull request, I am closing this issue, such that we track it there.

**Comment by jmakov** [comment]
Tracked here: https://github.com/the-tcpdump-group/tcpdump/pull/458
