### ISSUE TITLE
net.core.rmem_default too small?

### ISSUE THREAD

**Issue by CarstenGrohmann** [jmakov/gulp#7]
Hello Jernej,

the value of `rmem_default` is just 1/10 of the default in `tcp_rmem` (12582912 vs 125829120) is this intended or a typo?

https://github.com/jmakov/gulp/blob/33fcc15dca54411a154e0fa0aa909606cafb9c42/scripts/install.sh#L31-L32

Regards,
Carsten

**Comment by jmakov** [comment]
Yes. Thanks for finding this! Can you make a quick PR with a fix?
